/**
 * @vizel/core
 *
 * Framework-agnostic core for Vizel visual editor.
 * Built on top of Tiptap and ProseMirror.
 */

// Re-export Tiptap core for advanced usage
export { Editor, Editor as TiptapEditor } from "@tiptap/core";
export {
  BubbleMenuPlugin,
  default as BubbleMenuExtension,
} from "@tiptap/extension-bubble-menu";
// Auto-save
export {
  type AutoSaveOptions,
  type AutoSaveState,
  createAutoSaveHandlers,
  DEFAULT_AUTO_SAVE_OPTIONS,
  debounce,
  formatRelativeTime,
  getStorageBackend,
  type SaveStatus,
  type StorageBackend,
} from "./auto-save.ts";
// Extensions
export {
  addRecentColor,
  Blockquote,
  Bold,
  BulletList,
  CharacterCount,
  type CharacterCountStorage,
  Code,
  CodeBlock,
  type CodeBlockLanguage,
  CodeBlockLowlight,
  Color,
  type ColorDefinition,
  createCharacterCountExtension,
  createCodeBlockLowlightExtension,
  createDefaultFetchEmbedData,
  createEmbedExtension,
  createImageExtension,
  createImageUploadExtension,
  createImageUploader,
  createImageUploadPlugin,
  createLinkExtension,
  createMarkdownExtension,
  createMathematicsExtensions,
  createTableExtensions,
  createTaskListExtensions,
  createTextColorExtensions,
  createVizelExtensions,
  Document,
  Dropcursor,
  defaultEmbedProviders,
  defaultGroupOrder,
  defaultNodeTypes,
  defaultSlashCommands,
  detectProvider,
  Embed,
  type EmbedData,
  type EmbedProvider,
  type EmbedType,
  embedPastePluginKey,
  type FetchEmbedDataFn,
  filterSlashCommands,
  findLanguage,
  flattenSlashCommandGroups,
  Gapcursor,
  getActiveNodeType,
  getAllLanguageIds,
  getImageUploadPluginKey,
  getRecentColors,
  getRegisteredLanguages,
  groupSlashCommands,
  HardBreak,
  Heading,
  HIGHLIGHT_COLORS,
  Highlight,
  History,
  HorizontalRule,
  handleImageDrop,
  handleImagePaste,
  Image,
  ImageResize,
  type ImageResizeOptions,
  type ImageUploadOptions,
  type ImageValidationError,
  type ImageValidationErrorType,
  Italic,
  isValidHexColor,
  isValidUrl,
  katex,
  Link,
  ListItem,
  ListKeymap,
  lowlight,
  Markdown,
  MathBlock,
  MathInline,
  type NodeTypeOption,
  normalizeHexColor,
  OrderedList,
  Paragraph,
  Placeholder,
  ResizableImage,
  SlashCommand,
  type SlashCommandGroup,
  type SlashCommandItem,
  type SlashCommandOptions,
  type SlashCommandRange,
  type SlashCommandSearchResult,
  Strike,
  searchSlashCommands,
  Table,
  TableCell,
  TableHeader,
  TableRow,
  TaskItem,
  type TaskItemOptions,
  TaskList,
  type TaskListOptions,
  TEXT_COLORS,
  Text,
  TextStyle,
  TiptapMarkdown,
  Underline,
  type UploadImageFn,
  type VizelCharacterCountOptions,
  type VizelCodeBlockOptions,
  type VizelEmbedOptions,
  type VizelExtensionsOptions,
  type VizelImageOptions,
  type VizelImageUploadOptions,
  type VizelLinkOptions,
  type VizelMarkdownOptions,
  type VizelMathematicsOptions,
  type VizelTableOptions,
  type VizelTaskListOptions,
  type VizelTextColorOptions,
  validateImageFile,
} from "./extensions/index.ts";
// Theme
export {
  applyTheme,
  createSystemThemeListener,
  DEFAULT_THEME,
  DEFAULT_THEME_STORAGE_KEY,
  getStoredTheme,
  getSystemTheme,
  getThemeInitScript,
  type ResolvedTheme,
  resolveTheme,
  storeTheme,
  THEME_DATA_ATTRIBUTE,
  type Theme,
  type ThemeProviderOptions,
  type ThemeState,
} from "./theme.ts";
// Types
export type {
  Extensions,
  JSONContent,
  VizelEditorOptions,
  VizelEditorState,
  VizelFeatureOptions,
  VizelImageFeatureOptions,
  VizelSlashCommandOptions,
} from "./types.ts";
// Utilities
export {
  type CreateUploadEventHandlerOptions,
  createUploadEventHandler,
  defaultEditorProps,
  getEditorState,
  type ResolveFeaturesOptions,
  registerUploadEventHandler,
  resolveFeatures,
  VIZEL_UPLOAD_IMAGE_EVENT,
} from "./utils/index.ts";
