/**
 * @vizel/core
 *
 * Framework-agnostic core for Vizel visual editor.
 * Built on top of Tiptap and ProseMirror.
 */

// Re-export Tiptap core for advanced usage
export { Editor, Editor as TiptapEditor } from "@tiptap/core";
export {
  BubbleMenuPlugin,
  default as BubbleMenuExtension,
} from "@tiptap/extension-bubble-menu";
// Auto-save
export {
  type AutoSaveOptions,
  type AutoSaveState,
  createAutoSaveHandlers,
  DEFAULT_AUTO_SAVE_OPTIONS,
  debounce,
  formatRelativeTime,
  getStorageBackend,
  type SaveStatus,
  type StorageBackend,
} from "./auto-save.ts";
// Extensions
export {
  addRecentColor,
  Blockquote,
  Bold,
  BulletList,
  CharacterCount,
  type CharacterCountStorage,
  Code,
  CodeBlock,
  type CodeBlockLanguage,
  CodeBlockLowlight,
  Color,
  type ColorDefinition,
  createCharacterCountExtension,
  createCodeBlockLowlightExtension,
  createDefaultFetchEmbedData,
  createDetailsExtensions,
  createDiagramExtension,
  createEmbedExtension,
  createFileHandlerExtension,
  createImageExtension,
  createImageFileHandlers,
  createImageUploadExtension,
  createImageUploader,
  createImageUploadPlugin,
  createImageUploadWithFileHandler,
  createLinkExtension,
  createMarkdownExtension,
  createMathematicsExtensions,
  createTableExtensions,
  createTaskListExtensions,
  createTextColorExtensions,
  createVizelExtensions,
  DEFAULT_FILE_MIME_TYPES,
  Details,
  DetailsContent,
  type DetailsContentOptions,
  type DetailsNodeOptions,
  DetailsSummary,
  type DetailsSummaryOptions,
  Diagram,
  type DiagramType,
  Document,
  Dropcursor,
  defaultEmbedProviders,
  defaultGroupOrder,
  defaultNodeTypes,
  defaultSlashCommands,
  detectProvider,
  Embed,
  type EmbedData,
  type EmbedProvider,
  type EmbedType,
  embedPastePluginKey,
  type FetchEmbedDataFn,
  FileHandler,
  type FileHandlerError,
  type FileHandlerErrorType,
  filterFilesByMimeType,
  filterSlashCommands,
  findLanguage,
  flattenSlashCommandGroups,
  Gapcursor,
  getActiveNodeType,
  getAllLanguageIds,
  getImageUploadPluginKey,
  getRecentColors,
  getRegisteredLanguages,
  groupSlashCommands,
  HardBreak,
  Heading,
  HIGHLIGHT_COLORS,
  Highlight,
  History,
  HorizontalRule,
  handleImageDrop,
  handleImagePaste,
  Image,
  type ImageFileHandlerOptions,
  type ImageFileHandlers,
  ImageResize,
  type ImageResizeOptions,
  type ImageUploadOptions,
  type ImageValidationError,
  type ImageValidationErrorType,
  Italic,
  isValidHexColor,
  isValidUrl,
  katex,
  Link,
  ListItem,
  ListKeymap,
  lowlight,
  Markdown,
  MathBlock,
  MathInline,
  mermaid,
  type NodeTypeOption,
  normalizeHexColor,
  OrderedList,
  Paragraph,
  Placeholder,
  ResizableImage,
  SlashCommand,
  type SlashCommandGroup,
  type SlashCommandItem,
  type SlashCommandOptions,
  type SlashCommandRange,
  type SlashCommandSearchResult,
  Strike,
  searchSlashCommands,
  Table,
  TableCell,
  TableHeader,
  TableRow,
  TaskItem,
  type TaskItemOptions,
  TaskList,
  type TaskListOptions,
  TEXT_COLORS,
  Text,
  TextStyle,
  TiptapMarkdown,
  Underline,
  type UploadImageFn,
  type VizelCharacterCountOptions,
  type VizelCodeBlockOptions,
  type VizelDetailsOptions,
  type VizelDiagramOptions,
  type VizelEmbedOptions,
  type VizelExtensionsOptions,
  type VizelFileHandlerOptions,
  type VizelImageOptions,
  type VizelImageUploadOptions,
  type VizelImageUploadWithFileHandlerOptions,
  type VizelLinkOptions,
  type VizelMarkdownOptions,
  type VizelMathematicsOptions,
  type VizelTableOptions,
  type VizelTaskListOptions,
  type VizelTextColorOptions,
  validateImageFile,
} from "./extensions/index.ts";
// Theme
export {
  applyTheme,
  createSystemThemeListener,
  DEFAULT_THEME,
  DEFAULT_THEME_STORAGE_KEY,
  getStoredTheme,
  getSystemTheme,
  getThemeInitScript,
  type ResolvedTheme,
  resolveTheme,
  storeTheme,
  THEME_DATA_ATTRIBUTE,
  type Theme,
  type ThemeProviderOptions,
  type ThemeState,
} from "./theme.ts";
// Types
export type {
  Extensions,
  JSONContent,
  VizelEditorOptions,
  VizelEditorState,
  VizelFeatureOptions,
  VizelImageFeatureOptions,
  VizelSlashCommandOptions,
} from "./types.ts";
// Utilities
// Portal utilities
export {
  type ContentNode,
  type CreateUploadEventHandlerOptions,
  convertCodeBlocksToDiagrams,
  convertMermaidCodeBlocksToDiagrams,
  createPortalElement,
  createUploadEventHandler,
  defaultEditorProps,
  getEditorState,
  getPortalContainer,
  hasPortalContainer,
  type MountPortalOptions,
  mountToPortal,
  PORTAL_Z_INDEX,
  type PortalLayer,
  type ResolveFeaturesOptions,
  registerUploadEventHandler,
  removePortalContainer,
  resolveFeatures,
  transformDiagramCodeBlocks,
  transformMermaidToDiagram,
  unmountFromPortal,
  VIZEL_PORTAL_ID,
  VIZEL_UPLOAD_IMAGE_EVENT,
} from "./utils/index.ts";
