name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Related Package
      description: Which package would this feature apply to?
      options:
        - "@vizel/core"
        - "@vizel/react"
        - "@vizel/vue"
        - "@vizel/svelte"
        - "All packages"
        - "Not sure"
      multiple: true
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, mockups, or examples
    validations:
      required: false
