/**
 * @vizel/vue
 *
 * Vue 3 components and composables for the Vizel visual editor.
 */

// Re-export core types for convenience
export type {
  JSONContent,
  SlashCommandItem,
  SlashCommandOptions,
  VizelEditorOptions,
  VizelEditorState,
  VizelLinkOptions,
  VizelTableOptions,
} from "@vizel/core";

// Re-export core extensions and utilities
export {
  // Text color and highlight
  addRecentColor,
  Blockquote,
  Bold,
  BubbleMenuExtension,
  BulletList,
  CharacterCount,
  type CharacterCountStorage,
  Code,
  CodeBlock,
  type CodeBlockLanguage,
  CodeBlockLowlight,
  Color,
  type ColorDefinition,
  createCharacterCountExtension,
  createCodeBlockLowlightExtension,
  createImageExtension,
  createImageUploadExtension,
  createImageUploader,
  createImageUploadPlugin,
  createLinkExtension,
  createMathematicsExtensions,
  createTableExtensions,
  createTaskListExtensions,
  createTextColorExtensions,
  createVizelExtensions,
  Document,
  Dropcursor,
  defaultSlashCommands,
  Editor,
  filterSlashCommands,
  findLanguage,
  Gapcursor,
  getAllLanguageIds,
  getEditorState,
  getImageUploadPluginKey,
  getRecentColors,
  getRegisteredLanguages,
  HardBreak,
  Heading,
  HIGHLIGHT_COLORS,
  Highlight,
  History,
  HorizontalRule,
  handleImageDrop,
  handleImagePaste,
  Image,
  type ImageUploadOptions,
  type ImageValidationError,
  type ImageValidationErrorType,
  Italic,
  isValidHexColor,
  katex,
  Link,
  ListItem,
  ListKeymap,
  lowlight,
  MathBlock,
  MathInline,
  normalizeHexColor,
  OrderedList,
  Paragraph,
  Placeholder,
  SlashCommand,
  Strike,
  Table,
  TableCell,
  TableHeader,
  TableRow,
  TaskItem,
  type TaskItemOptions,
  TaskList,
  type TaskListOptions,
  TEXT_COLORS,
  Text,
  TextStyle,
  type UploadImageFn,
  type VizelCharacterCountOptions,
  type VizelCodeBlockOptions,
  type VizelExtensionsOptions,
  type VizelImageOptions,
  type VizelImageUploadOptions,
  type VizelMathematicsOptions,
  type VizelTaskListOptions,
  type VizelTextColorOptions,
  validateImageFile,
} from "@vizel/core";

// Components
export {
  BubbleMenu,
  BubbleMenuButton,
  type BubbleMenuButtonProps,
  BubbleMenuColorPicker,
  type BubbleMenuColorPickerProps,
  BubbleMenuDivider,
  type BubbleMenuDividerProps,
  BubbleMenuLinkEditor,
  type BubbleMenuLinkEditorProps,
  type BubbleMenuProps,
  BubbleMenuToolbar,
  type BubbleMenuToolbarProps,
  EditorContent,
  type EditorContentProps,
  EditorRoot,
  type EditorRootProps,
  SlashMenu,
  SlashMenuEmpty,
  type SlashMenuEmptyProps,
  SlashMenuItem,
  type SlashMenuItemProps,
  type SlashMenuProps,
  type SlashMenuRef,
  useEditorContext,
  useEditorContextSafe,
} from "./components/index.ts";

// Composables
export {
  createSlashMenuRenderer,
  type SlashMenuRendererOptions,
  type UseVizelEditorOptions,
  useEditorState,
  useVizelEditor,
} from "./composables/index.ts";
