import type { VizelCommand } from "../types.ts";

/**
 * Block-level commands that change the current block's node type
 * (headings, lists, quote, code block, divider, details, callout).
 *
 * These commands appear in the slash menu and have shortcuts for the
 * common cases. They do not appear in the toolbar's default action
 * row; toolbar surfaces them through the node-type dropdown instead.
 */
export const vizelBlockCommands: readonly VizelCommand[] = [
  // Headings
  {
    id: "block/heading1",
    label: (locale) => locale.slashMenu.items.heading1.title,
    description: (locale) => locale.slashMenu.items.heading1.description,
    icon: "heading1",
    group: "Text",
    keywords: ["h1", "title", "header", "big"],
    shortcut: { mac: "Mod-Alt-1", other: "Mod-Alt-1" },
    canRun: (editor) => editor.can().setNode("heading", { level: 1 }),
    isActive: (editor) => editor.isActive("heading", { level: 1 }),
    run: (editor) => editor.chain().focus().setNode("heading", { level: 1 }).run(),
    surfaces: {
      slashMenu: { priority: 10 },
      shortcut: true,
    },
  },
  {
    id: "block/heading2",
    label: (locale) => locale.slashMenu.items.heading2.title,
    description: (locale) => locale.slashMenu.items.heading2.description,
    icon: "heading2",
    group: "Text",
    keywords: ["h2", "subtitle", "header"],
    shortcut: { mac: "Mod-Alt-2", other: "Mod-Alt-2" },
    canRun: (editor) => editor.can().setNode("heading", { level: 2 }),
    isActive: (editor) => editor.isActive("heading", { level: 2 }),
    run: (editor) => editor.chain().focus().setNode("heading", { level: 2 }).run(),
    surfaces: {
      slashMenu: { priority: 20 },
      shortcut: true,
    },
  },
  {
    id: "block/heading3",
    label: (locale) => locale.slashMenu.items.heading3.title,
    description: (locale) => locale.slashMenu.items.heading3.description,
    icon: "heading3",
    group: "Text",
    keywords: ["h3", "header", "section"],
    shortcut: { mac: "Mod-Alt-3", other: "Mod-Alt-3" },
    canRun: (editor) => editor.can().setNode("heading", { level: 3 }),
    isActive: (editor) => editor.isActive("heading", { level: 3 }),
    run: (editor) => editor.chain().focus().setNode("heading", { level: 3 }).run(),
    surfaces: {
      slashMenu: { priority: 30 },
      shortcut: true,
    },
  },
  {
    id: "block/heading4",
    label: (locale) => locale.slashMenu.items.heading4.title,
    description: (locale) => locale.slashMenu.items.heading4.description,
    icon: "heading4",
    group: "Text",
    keywords: ["h4", "header", "subsection"],
    shortcut: { mac: "Mod-Alt-4", other: "Mod-Alt-4" },
    canRun: (editor) => editor.can().setNode("heading", { level: 4 }),
    isActive: (editor) => editor.isActive("heading", { level: 4 }),
    run: (editor) => editor.chain().focus().setNode("heading", { level: 4 }).run(),
    surfaces: {
      slashMenu: { priority: 40 },
      shortcut: true,
    },
  },
  {
    id: "block/heading5",
    label: (locale) => locale.slashMenu.items.heading5.title,
    description: (locale) => locale.slashMenu.items.heading5.description,
    icon: "heading5",
    group: "Text",
    keywords: ["h5", "header", "minor"],
    shortcut: { mac: "Mod-Alt-5", other: "Mod-Alt-5" },
    canRun: (editor) => editor.can().setNode("heading", { level: 5 }),
    isActive: (editor) => editor.isActive("heading", { level: 5 }),
    run: (editor) => editor.chain().focus().setNode("heading", { level: 5 }).run(),
    surfaces: {
      slashMenu: { priority: 50 },
      shortcut: true,
    },
  },
  {
    id: "block/heading6",
    label: (locale) => locale.slashMenu.items.heading6.title,
    description: (locale) => locale.slashMenu.items.heading6.description,
    icon: "heading6",
    group: "Text",
    keywords: ["h6", "header", "smallest"],
    shortcut: { mac: "Mod-Alt-6", other: "Mod-Alt-6" },
    canRun: (editor) => editor.can().setNode("heading", { level: 6 }),
    isActive: (editor) => editor.isActive("heading", { level: 6 }),
    run: (editor) => editor.chain().focus().setNode("heading", { level: 6 }).run(),
    surfaces: {
      slashMenu: { priority: 60 },
      shortcut: true,
    },
  },
  // Lists
  {
    id: "block/bulletList",
    label: (locale) => locale.slashMenu.items.bulletList.title,
    description: (locale) => locale.slashMenu.items.bulletList.description,
    icon: "bulletList",
    group: "Lists",
    keywords: ["ul", "unordered", "bullets", "points"],
    shortcut: { mac: "Mod-Shift-8", other: "Mod-Shift-8" },
    canRun: (editor) => editor.can().toggleBulletList(),
    isActive: (editor) => editor.isActive("bulletList"),
    run: (editor) => editor.chain().focus().toggleBulletList().run(),
    surfaces: {
      slashMenu: { priority: 100 },
      shortcut: true,
    },
  },
  {
    id: "block/orderedList",
    label: (locale) => locale.slashMenu.items.numberedList.title,
    description: (locale) => locale.slashMenu.items.numberedList.description,
    icon: "orderedList",
    group: "Lists",
    keywords: ["ol", "ordered", "numbers", "steps"],
    shortcut: { mac: "Mod-Shift-7", other: "Mod-Shift-7" },
    canRun: (editor) => editor.can().toggleOrderedList(),
    isActive: (editor) => editor.isActive("orderedList"),
    run: (editor) => editor.chain().focus().toggleOrderedList().run(),
    surfaces: {
      slashMenu: { priority: 110 },
      shortcut: true,
    },
  },
  {
    id: "block/taskList",
    label: (locale) => locale.slashMenu.items.taskList.title,
    description: (locale) => locale.slashMenu.items.taskList.description,
    icon: "taskList",
    group: "Lists",
    keywords: ["todo", "checkbox", "checklist", "tasks"],
    canRun: (editor) => editor.can().toggleTaskList?.() ?? false,
    isActive: (editor) => editor.isActive("taskList"),
    run: (editor) => editor.chain().focus().toggleTaskList().run(),
    surfaces: {
      slashMenu: { priority: 120 },
    },
  },
  // Blocks
  {
    id: "block/quote",
    label: (locale) => locale.slashMenu.items.quote.title,
    description: (locale) => locale.slashMenu.items.quote.description,
    icon: "blockquote",
    group: "Blocks",
    keywords: ["blockquote", "citation", "cite"],
    shortcut: { mac: "Mod-Shift-B", other: "Mod-Shift-B" },
    canRun: (editor) => editor.can().toggleBlockquote(),
    isActive: (editor) => editor.isActive("blockquote"),
    run: (editor) => editor.chain().focus().toggleBlockquote().run(),
    surfaces: {
      slashMenu: { priority: 200 },
      shortcut: true,
    },
  },
  {
    id: "block/codeBlock",
    label: (locale) => locale.slashMenu.items.codeBlock.title,
    description: (locale) => locale.slashMenu.items.codeBlock.description,
    icon: "codeBlock",
    group: "Blocks",
    keywords: ["pre", "code", "programming", "syntax", "snippet"],
    shortcut: { mac: "Mod-Alt-C", other: "Mod-Alt-C" },
    canRun: (editor) => editor.can().toggleCodeBlock(),
    isActive: (editor) => editor.isActive("codeBlock"),
    run: (editor) => editor.chain().focus().toggleCodeBlock().run(),
    surfaces: {
      slashMenu: { priority: 210 },
      shortcut: true,
    },
  },
  {
    id: "block/divider",
    label: (locale) => locale.slashMenu.items.divider.title,
    description: (locale) => locale.slashMenu.items.divider.description,
    icon: "horizontalRule",
    group: "Blocks",
    keywords: ["hr", "horizontal", "line", "separator", "break"],
    canRun: (editor) => editor.can().setHorizontalRule(),
    run: (editor) => editor.chain().focus().setHorizontalRule().run(),
    surfaces: {
      slashMenu: { priority: 220 },
    },
  },
  {
    id: "block/details",
    label: (locale) => locale.slashMenu.items.details.title,
    description: (locale) => locale.slashMenu.items.details.description,
    icon: "details",
    group: "Blocks",
    keywords: ["accordion", "toggle", "collapse", "expand", "summary", "details"],
    canRun: (editor) => editor.can().setDetails?.() ?? false,
    isActive: (editor) => editor.isActive("details"),
    run: (editor) => editor.chain().focus().setDetails().run(),
    surfaces: {
      slashMenu: { priority: 230 },
    },
  },
  {
    id: "block/callout",
    label: (locale) => locale.slashMenu.items.callout.title,
    description: (locale) => locale.slashMenu.items.callout.description,
    icon: "callout",
    group: "Blocks",
    keywords: ["callout", "admonition", "alert", "info", "warning", "danger", "tip", "note"],
    canRun: (editor) => editor.can().setCallout?.({ type: "info" }) ?? false,
    isActive: (editor) => editor.isActive("callout"),
    run: (editor) => editor.chain().focus().setCallout({ type: "info" }).run(),
    surfaces: {
      slashMenu: { priority: 240 },
    },
  },
];
